### ISSUE TITLE
/status.json not found

### ISSUE THREAD

**Issue by marcelstoer** [jeanralphaviles/dump1090-docker#2] opened 2019-12-17 21:11 UTC
PiAware Skyview at http://localhost:8080 loads `/status.json` in `./public_html/script.js` which fails with HTTP 404. Not sure if this is an issue with dump1090-fa from @flightaware or this image.

**Comment by jeanralphaviles** [comment] 2019-12-20 04:54
Fired up the docker container and yeah, I remember `/status.json` being a problem. There is also `upintheair.json` which cannot be found. This comes from [flightaware/dump1090](https://github.com/flightaware/dump1090), not from my version of it. Otherwise everything works just fine.

I updated the docker image, but the problem is still there.

Looking through the code it looks like this `/status.json` file is used to signal to the UI that it is running a [Flightaware Flightfeeder](https://flightaware.com/adsb/flightfeeder/) and it should change its branding to match. It's purely a marketing thing.

Code: https://github.com/flightaware/dump1090/blob/master/public_html/script.js#L1882-L1906. You can see that the only action it takes is to change the name of the Page from "PiAware Skyview" to "FlightFeeder Skyaware".

See also the commit that introduced it: https://github.com/flightaware/dump1090/commit/ee23816428599202dd304d0a4f250e04ae36e0d3.

I'll close this issue as it can't be fixed here. It doesn't break anything, just causes some console log spam.

**Closed as completed by jeanralphaviles** 2019-12-20 04:54 UTC

**Comment by marcelstoer** [comment] 2019-12-20 06:36
Thanks for the analysis!

> it can't be fixed here

It can - modifying `script.js` with `sed` or the like during the build - but it's probably not worth it. However, I guess mentioning this behavior in the README probably would be appreciated by (some) users.

**Comment by marcelstoer** [comment] 2019-12-20 21:35
> I updated the docker image

Any chance you can bring back the arm/v7 version at `latest`? That one somehow seems to have got lost.

**Comment by jeanralphaviles** [comment] 2019-12-22 02:43
`Any chance you can bring back the arm/v7 version at latest? That one somehow seems to have got lost.`
I was having trouble with my Raspberry Pi, that's how I was building the arm/v7 image. I need to get that up and running again.

**Comment by marcelstoer** [comment] 2019-12-22 10:14
> I need to get that up and running again.

Not necessarily 😉 https://frightanic.com/computers/docker-buildx-the-best-thing-since-sliced-bread/

**Comment by jeanralphaviles** [comment] 2019-12-28 16:38
Followed instructions here: https://docs.docker.com/buildx/working-with-buildx.

1. Installed Docker 19.03
1. export DOCKER_CLI_EXPERIMENTAL=enabled 
1. docker buildx create --use --name my-builder
1. docker buildx build --push --platform linux/amd64,linux/arm64 -t jraviles/dump1090:latest .

Is the updated image working for you? It includes this PR.

**Comment by marcelstoer** [comment] 2019-12-28 16:41
Could you please build & push again and also include `linux/arm/v7`? That one is required for older Pi installations.

**Comment by jeanralphaviles** [comment] 2019-12-28 16:46
Forgot to include liux/arm/v7. Building it now.

$ docker buildx build --push --platform linux/amd64,linux/arm64,linux/arm/v7 -t jraviles/dump1090:latest .
